### ISSUE TITLE
Windows 10 ThreadException

### ISSUE THREAD

**Issue by Sponge97** [Codeusa/Borderless-Gaming#191]
Everytime I run Borderless-Gaming I get an error. No windows can be used by the application, rendering it useless. I also get the same error log everytime.

The error file can be found here: http://pastebin.com/5MMrL0y2

**Comment by YabbaTroll** [comment]
I'm having the same problem here on windows 10
All my info is right here https://steamcommunity.com/app/388080/discussions/1/535152511352343566/

**Comment by psouza4** [comment]
This is caused by a corrupt favorites file.  Will roll out a fix before long.

**Comment by psouza4** [comment]
Resolved in version 8.3.

**Comment by Acecool** [comment]
The exception resolves nothing because favorites still don't load even if all folders exist ( and registry too ).

https://github.com/Codeusa/Borderless-Gaming/issues/225
